### ISSUE TITLE
Wrong alignment for permission dialog checkmarks

### ISSUE THREAD

**Issue by beyondsanity** [nearit/iOS-UI-Bindings#4]
Checkmarks should be aligned left (label should stay centered).
![simulator screen shot - iphone 6 - 2017-10-30 at 14 53 45](https://user-images.githubusercontent.com/7868362/32174760-07b0a8a2-bd83-11e7-942c-e908953e3bf4.png)

**Comment by nferruzzi** [comment]
ok

**Comment by nferruzzi** [comment]
fixed in https://github.com/nearit/iOS-UI-Bindings/pull/9
